"""
Technology taxonomy and categorization utility for AI Placement Copilot.
Maps raw skill names, framework aliases, and topics into canonical names and 10 technical categories.
"""
from typing import Dict, Optional, Tuple

# Mapping of canonical skill name -> canonical category
TECH_TAXONOMY: Dict[str, str] = {
    # 1. Programming Languages
    "Python": "programming",
    "Java": "programming",
    "C++": "programming",
    "C": "programming",
    "C#": "programming",
    "JavaScript": "programming",
    "TypeScript": "programming",
    "Go": "programming",
    "Rust": "programming",
    "Kotlin": "programming",
    "Swift": "programming",
    "PHP": "programming",
    "Ruby": "programming",
    "Scala": "programming",
    "R": "programming",
    "Dart": "programming",
    "Bash": "programming",
    "Shell": "programming",
    "SQL": "programming",
    "HTML/CSS": "programming",

    # 2. DSA (Data Structures & Algorithms)
    "Arrays": "dsa",
    "Strings": "dsa",
    "Linked Lists": "dsa",
    "Stack": "dsa",
    "Queue": "dsa",
    "Binary Search": "dsa",
    "Trees": "dsa",
    "Binary Trees": "dsa",
    "Binary Search Trees": "dsa",
    "Graphs": "dsa",
    "Dynamic Programming": "dsa",
    "Greedy": "dsa",
    "Backtracking": "dsa",
    "Sorting": "dsa",
    "Hashing": "dsa",
    "Heaps": "dsa",
    "Trie": "dsa",
    "Bit Manipulation": "dsa",
    "Two Pointers": "dsa",
    "Sliding Window": "dsa",
    "Recursion": "dsa",
    "Divide and Conquer": "dsa",
    "Data Structures & Algorithms": "dsa",

    # 3. Backend
    "FastAPI": "backend",
    "Flask": "backend",
    "Django": "backend",
    "Node.js": "backend",
    "Express.js": "backend",
    "Spring Boot": "backend",
    "NestJS": "backend",
    "Ruby on Rails": "backend",
    "ASP.NET": "backend",
    "GraphQL": "backend",
    "REST API": "backend",
    "RESTful APIs": "backend",
    "Microservices": "backend",
    "gRPC": "backend",
    "Celery": "backend",
    "RabbitMQ": "backend",
    "Kafka": "backend",

    # 4. Frontend
    "React": "frontend",
    "Next.js": "frontend",
    "Vue.js": "frontend",
    "Angular": "frontend",
    "Svelte": "frontend",
    "HTML": "frontend",
    "CSS": "frontend",
    "Tailwind CSS": "frontend",
    "Bootstrap": "frontend",
    "Redux": "frontend",
    "Zustand": "frontend",
    "Vite": "frontend",
    "Webpack": "frontend",
    "UI/UX Design": "frontend",

    # 5. Machine Learning
    "TensorFlow": "machine_learning",
    "PyTorch": "machine_learning",
    "Scikit-learn": "machine_learning",
    "Keras": "machine_learning",
    "OpenCV": "machine_learning",
    "Hugging Face": "machine_learning",
    "NLP": "machine_learning",
    "Natural Language Processing": "machine_learning",
    "Computer Vision": "machine_learning",
    "Deep Learning": "machine_learning",
    "Machine Learning": "machine_learning",
    "XGBoost": "machine_learning",
    "Transformers": "machine_learning",
    "LangChain": "machine_learning",
    "LLMs": "machine_learning",
    "Large Language Models": "machine_learning",

    # 6. Data Science
    "Pandas": "data_science",
    "NumPy": "data_science",
    "Matplotlib": "data_science",
    "Seaborn": "data_science",
    "SciPy": "data_science",
    "Jupyter": "data_science",
    "Data Analysis": "data_science",
    "Exploratory Data Analysis": "data_science",
    "Tableau": "data_science",
    "Power BI": "data_science",
    "Statistics": "data_science",
    "BigQuery": "data_science",

    # 7. Databases
    "PostgreSQL": "databases",
    "MySQL": "databases",
    "MongoDB": "databases",
    "Redis": "databases",
    "SQLite": "databases",
    "Oracle": "databases",
    "Cassandra": "databases",
    "Elasticsearch": "databases",
    "DynamoDB": "databases",
    "MariaDB": "databases",
    "Neo4j": "databases",
    "Firebase": "databases",
    "Prisma": "databases",
    "SQLAlchemy": "databases",

    # 8. DevOps
    "Docker": "devops",
    "Kubernetes": "devops",
    "CI/CD": "devops",
    "GitHub Actions": "devops",
    "Jenkins": "devops",
    "Terraform": "devops",
    "Ansible": "devops",
    "Linux": "devops",
    "Nginx": "devops",
    "Prometheus": "devops",
    "Grafana": "devops",
    "Helm": "devops",

    # 9. Cloud
    "AWS": "cloud",
    "Google Cloud Platform": "cloud",
    "Microsoft Azure": "cloud",
    "AWS Lambda": "cloud",
    "Amazon S3": "cloud",
    "Amazon EC2": "cloud",
    "Cloudflare": "cloud",
    "Vercel": "cloud",
    "Netlify": "cloud",
    "Serverless": "cloud",
    "GCP Cloud Run": "cloud",

    # 10. CS Fundamentals
    "Operating Systems": "cs_fundamentals",
    "DBMS": "cs_fundamentals",
    "Database Management Systems": "cs_fundamentals",
    "Computer Networks": "cs_fundamentals",
    "System Design": "cs_fundamentals",
    "Low Level Design": "cs_fundamentals",
    "High Level Design": "cs_fundamentals",
    "Object-Oriented Programming": "cs_fundamentals",
    "OOP": "cs_fundamentals",
    "Software Engineering": "cs_fundamentals",
    "Compiler Design": "cs_fundamentals",
    "Theory of Computation": "cs_fundamentals",
}

# Alias / Normalization lookup: maps lowercase alias -> canonical name
ALIAS_LOOKUP: Dict[str, str] = {
    "py": "Python",
    "python": "Python",
    "python3": "Python",
    "java": "Java",
    "cpp": "C++",
    "c++": "C++",
    "c": "C",
    "c#": "C#",
    "csharp": "C#",
    "js": "JavaScript",
    "javascript": "JavaScript",
    "ts": "TypeScript",
    "typescript": "TypeScript",
    "golang": "Go",
    "go": "Go",
    "rust": "Rust",
    "kotlin": "Kotlin",
    "swift": "Swift",
    "php": "PHP",
    "ruby": "Ruby",
    "scala": "Scala",
    "r": "R",
    "dart": "Dart",
    "bash": "Bash",
    "shell": "Shell",
    "sql": "SQL",

    # DSA
    "dsa": "Data Structures & Algorithms",
    "data structures": "Data Structures & Algorithms",
    "algorithms": "Data Structures & Algorithms",
    "array": "Arrays",
    "arrays": "Arrays",
    "string": "Strings",
    "strings": "Strings",
    "linked list": "Linked Lists",
    "linked lists": "Linked Lists",
    "stack": "Stack",
    "queue": "Queue",
    "tree": "Trees",
    "trees": "Trees",
    "binary tree": "Binary Trees",
    "binary search tree": "Binary Search Trees",
    "bst": "Binary Search Trees",
    "graph": "Graphs",
    "graphs": "Graphs",
    "dp": "Dynamic Programming",
    "dynamic programming": "Dynamic Programming",
    "binary search": "Binary Search",
    "greedy": "Greedy",
    "backtracking": "Backtracking",
    "sorting": "Sorting",
    "hashing": "Hashing",
    "hash table": "Hashing",
    "heap": "Heaps",
    "heaps": "Heaps",
    "trie": "Trie",
    "recursion": "Recursion",

    # Backend
    "fastapi": "FastAPI",
    "flask": "Flask",
    "django": "Django",
    "node": "Node.js",
    "nodejs": "Node.js",
    "node.js": "Node.js",
    "express": "Express.js",
    "expressjs": "Express.js",
    "express.js": "Express.js",
    "spring": "Spring Boot",
    "springboot": "Spring Boot",
    "spring boot": "Spring Boot",
    "nestjs": "NestJS",
    "rails": "Ruby on Rails",
    "ruby on rails": "Ruby on Rails",
    "rest": "REST API",
    "rest api": "REST API",
    "rest apis": "RESTful APIs",
    "restful": "RESTful APIs",
    "graphql": "GraphQL",
    "grpc": "gRPC",
    "microservices": "Microservices",
    "celery": "Celery",
    "kafka": "Kafka",
    "rabbitmq": "RabbitMQ",

    # Frontend
    "react": "React",
    "reactjs": "React",
    "react.js": "React",
    "next": "Next.js",
    "nextjs": "Next.js",
    "next.js": "Next.js",
    "vue": "Vue.js",
    "vuejs": "Vue.js",
    "vue.js": "Vue.js",
    "angular": "Angular",
    "angularjs": "Angular",
    "svelte": "Svelte",
    "html": "HTML",
    "css": "CSS",
    "html5": "HTML",
    "css3": "CSS",
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "tailwind css": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "redux": "Redux",
    "zustand": "Zustand",
    "vite": "Vite",
    "webpack": "Webpack",

    # Machine Learning
    "tensorflow": "TensorFlow",
    "tf": "TensorFlow",
    "pytorch": "PyTorch",
    "torch": "PyTorch",
    "scikit-learn": "Scikit-learn",
    "sklearn": "Scikit-learn",
    "keras": "Keras",
    "opencv": "OpenCV",
    "cv": "Computer Vision",
    "computer vision": "Computer Vision",
    "nlp": "Natural Language Processing",
    "natural language processing": "Natural Language Processing",
    "deep learning": "Deep Learning",
    "machine learning": "Machine Learning",
    "ml": "Machine Learning",
    "xgboost": "XGBoost",
    "huggingface": "Hugging Face",
    "hugging face": "Hugging Face",
    "transformers": "Transformers",
    "langchain": "LangChain",
    "llm": "LLMs",
    "llms": "LLMs",
    "large language models": "Large Language Models",

    # Data Science
    "pandas": "Pandas",
    "numpy": "NumPy",
    "matplotlib": "Matplotlib",
    "seaborn": "Seaborn",
    "scipy": "SciPy",
    "jupyter": "Jupyter",
    "data analysis": "Data Analysis",
    "eda": "Exploratory Data Analysis",
    "tableau": "Tableau",
    "powerbi": "Power BI",
    "power bi": "Power BI",
    "statistics": "Statistics",
    "bigquery": "BigQuery",

    # Databases
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "mysql": "MySQL",
    "mongo": "MongoDB",
    "mongodb": "MongoDB",
    "redis": "Redis",
    "sqlite": "SQLite",
    "oracle": "Oracle",
    "cassandra": "Cassandra",
    "elasticsearch": "Elasticsearch",
    "dynamodb": "DynamoDB",
    "mariadb": "MariaDB",
    "neo4j": "Neo4j",
    "firebase": "Firebase",
    "prisma": "Prisma",
    "sqlalchemy": "SQLAlchemy",

    # DevOps
    "docker": "Docker",
    "k8s": "Kubernetes",
    "kubernetes": "Kubernetes",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "github actions": "GitHub Actions",
    "jenkins": "Jenkins",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "linux": "Linux",
    "nginx": "Nginx",
    "prometheus": "Prometheus",
    "grafana": "Grafana",
    "helm": "Helm",

    # Cloud
    "aws": "AWS",
    "gcp": "Google Cloud Platform",
    "google cloud": "Google Cloud Platform",
    "azure": "Microsoft Azure",
    "lambda": "AWS Lambda",
    "aws lambda": "AWS Lambda",
    "s3": "Amazon S3",
    "ec2": "Amazon EC2",
    "cloudflare": "Cloudflare",
    "vercel": "Vercel",
    "netlify": "Netlify",
    "serverless": "Serverless",

    # CS Fundamentals
    "os": "Operating Systems",
    "operating systems": "Operating Systems",
    "operating system": "Operating Systems",
    "dbms": "DBMS",
    "database management": "DBMS",
    "database management systems": "DBMS",
    "cn": "Computer Networks",
    "computer networks": "Computer Networks",
    "networking": "Computer Networks",
    "system design": "System Design",
    "lld": "Low Level Design",
    "hld": "High Level Design",
    "oop": "Object-Oriented Programming",
    "oops": "Object-Oriented Programming",
    "object oriented programming": "Object-Oriented Programming",
    "software engineering": "Software Engineering",
}


def normalize_skill_name(raw_name: str) -> Tuple[str, str]:
    """
    Normalizes a raw skill name to its canonical form and category.
    Returns (canonical_name, category).
    If unknown, category defaults to 'programming' or 'cs_fundamentals' / 'other'.
    """
    if not raw_name:
        return "", "programming"
    clean = raw_name.strip()
    lookup_key = clean.lower().replace("_", " ").replace("-", " ")
    
    # Try exact lookup in alias table
    canonical = ALIAS_LOOKUP.get(clean.lower()) or ALIAS_LOOKUP.get(lookup_key)
    if not canonical:
        # Check if already canonical in taxonomy
        if clean in TECH_TAXONOMY:
            canonical = clean
        else:
            canonical = clean.title() if len(clean) > 3 else clean.upper()

    category = TECH_TAXONOMY.get(canonical, "programming")
    return canonical, category
